kolomiets_my_homepage:
    path:     /
    defaults: { _controller: KolomietsMyBundle:Default:index }

kolomiets_my_default:
    path:     /say_hello
    defaults: { _controller: KolomietsMyBundle:Default:hello }

kolomiets_my_string:
    path:     /text/{text}
    defaults: { _controller: KolomietsMyBundle:Default:text, text: 'default' }

kolomiets_my_default_string:
    path:     /summ/{number1}/{number2}
    defaults: { _controller: KolomietsMyBundle:Default:summ, number2: 10 }
    requirements:
        number1: '\d'
        number2: '\d+'

kolomiets_my_personal:
    path:     /personal/{name}/{age}
    defaults: { _controller: KolomietsMyBundle:Default:personal, age: 'Not set' }
    requirements:
        age: '\d+'
